config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :widgets, only: %i[show index new create] do
    resources :ratings, only: [:create]
  end
  resources :widget_ratings, only: [:create]

  namespace :customer_service do
    resources :widgets, only: %i[show update destroy]
  end

  resources :design_system_docs, only: [:index] if Rails.env.development?

  # Custom routes start here
  get 'manufacturer/:id', to: 'manufacturers#show'

  # Root path
  root to: 'widgets#index'
end

app/models/address.rb
# frozen_string_literal: true

#
# address.rb
# Copyright (C) 2023 tinix <tinix@archlinux>
#
# Distributed under terms of the MIT license.
#
class Address < ApplicationRecord
  # Associations
  has_many :manufacturers
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory_report.rb
# frozen_string_literal: true

class InventoryReport < ApplicationRecord
end

app/models/manufacturer.rb
# frozen_string_literal: true

class Manufacturer < ApplicationRecord
  # Associations
  has_many :widgets
  belongs_to :address
end

app/models/widget.rb
# frozen_string_literal: true

class Widget < ApplicationRecord
  # Associations
  belongs_to :manufacturer
  belongs_to :widgets_status

  # Validations
  validates :name, presence: true
  validates :price_cents,
            numericality: { less_than_or_equal_to: 10_000_00 }

  before_validation do
    self.name = nil if name.blank?
  end

  def self.fresh
    where(status: 'fresh')
  end

  def user_facing_identifier
    id_has_string = id.to_s
    return id_has_string if id_has_string.length < 3

    format('%<first>s. %<last_two>s', first: id_has_string[0..-3], last_two: id_has_string[-2..])
  end
end

app/models/widget_status.rb
# frozen_string_literal: true

#
# widget_status.rb
# Copyright (C) 2023 tinix <tinix@archlinux>
#
# Distributed under terms of the MIT license.
#
class WidgetStatus < ApplicationRecord
  # Associations
  has_many :widgets
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/design_system_docs_controller.rb
# frozen_string_literal: true

#
# design_system_docs_controller.rb
# Copyright (C) 2023 tinix <tinix@archlinux>
#
# Distributed under terms of the MIT license.
class DesignSystemDocsController < ApplicationController
  def index
    @design_system_docs = OpenStruct.new(
      font_sizes: %w[
        f-headline
        f-subheadline
        f1
        f2
        f3
        f4
        f5
        f6
      ],
      sizes: [1, 2, 3, 4, 5],
      colors: {
        text: 'near-black',
        green: 'dark-green',
        red: 'dark-red',
        orange: 'orange'
      }
    )
  end
end

app/controllers/widget_ratings_controller.rb
# frozen_string_literal: true

#
# widget_ratings_controller.rb
# Copyright (C) 2023 tinix <tinix@archlinux>
#
# Distributed under terms of the MIT license.
#
#
class WidgetRatingsController < ApplicationController
  def create
    if params[:widget_id]
      # find the widget and update its rating
      redirect_to widget_path(params[:widget_id]),
                  flash[:notice] = 'Thanks for rating!'
    else
      head :bad_request
    end
  end
end

app/controllers/widgets_controller.rb
# frozen_string_literal: true

#
# widgets_controller.rb
# Copyright (C) 2023 tinix <tinix@archlinux>
#
# Distributed under terms of the MIT license.
#
class WidgetsController < ApplicationController
  before_action :set_widget, only: %i[show edit update destroy]

  def index
    @widgets = [
      OpenStruct.new(id: 1234, name: 'Stembolt'),
      OpenStruct.new(id: 2, name: 'Flux Capacitor')
    ]
  end

  def edit; end

  def new
    @widget = Widget.new
    @manufacturers = Manufacturer.all
  end

  def create
    render plain: "Thanks"
  end

  def show
    manofacturer = OpenStruct.new(
      id: rand(100),
      name: 'Sector 7G',
      address: OpenStruct.new(
        id: rand(100),
        country: 'AR'
      )
    )
    widget_name = if params[:id].to_i == 1234
                    'Stembolt'
                  else
                    "Widget #{params[:id]}"
                  end
    @widget = OpenStruct.new(id: params[:id],
                             manufacturer_id: manufacturer.id,
                             manufacturer: manufacturer,
                             name: widegt_name)
    def @midget.widget_id
      if id.to_s.length < 3
        id.to_s
      else
        "#{id.to_s[0..-3]}.#{id.to_s[-2..]}"
      end
    end
    @widget_presenter = WidgetPresenter.new(widget)
  end

  def update
    if params[:widget][:rating].present?
      # update the rating
    else
      # do some other sort of update
    end

    @widget = WidgetEditingService.new.edit_widget(
      widget, widget_params
    )

    if @widget.valid?
      redirect_to widgets_path
    else
      render :edit
    end
  end

  private

  def set_widget
    @widget = Widget.find(params[:id])
  end

  def widget_params
    params.require(:widget).permit(:name, :status, :type)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def widget_ratings_component(_widget, suppress_cta: false)
    render partial: 'widgets/rating',
           locals: { widget_presenter: @widget_presenter, suppress_cta: suppress_cta }
  end

  def styled_midget_id(formatted_id)
    %(
      <span style=\"font-family: monospace\">
        #{formatted_id}
      </span>
    ).html_safe
  end
end

app/views/design_system_docs/index.html.erb
<section class="pa3">
	<h1>
		Design System Docs
		<nav class="f4 di ml3">
			<a href="#font-sizes">Font Sizes</a> |
			<a href="#sizes">Sizes</a> |
			<a href="#colors">Colors</a> |
			<a href="https://tachyons.io/docs/">Tachyons Docs</a>
		</nav>
	</h1>
	<a name="font-sizes">
		<h2>Font Sizes</h2>
		<% @design_system_docs.font_sizes.
			each do |font_size_css_class| %>
			<p class="<%= font_size_css_class %> mt0 mb0">
				<%= font_size_css_class %> Font Size
			</p>
			<code><pre>
&lt;p class="<%= font_size_css_class %>"&gt;
<%= font_size_css_class %> Font Size
&lt;/p&gt;
			</pre></code>
		<% end %>
		<a name="sizes">
			<h2>Sizes</h2>
			<% @design_system_docs.sizes.each do |size_number| %>
				<h3>Size <%= size_number %></h3>
				<div class="pa<%= size_number %> ba
				h<%= size_number %>
			w<%= size_number %> bg-gray">
			&nbsp;

				</div>
				<code><pre>
&lt;div class="pa<%= size_number %>"&gt;
Padding all sides
&lt;/div&gt;
&lt;div class="ma<%= size_number %>"&gt;
Margin all sides
&lt;/div&gt;
				</pre></code>
			<% end %>
			<a name="colors">
				<h2>Colors</h2>
				<% @design_system_docs.colors.each do |name, css_class| %>
					<h3><%= name.to_s.humanize %></h3>
					<div class="ma1 pv3 ph2 h4 bg-<%= css_class %> white">
						<code><pre>
&lt;div class="bg-<%= css_class %>"&gt;
<%= name %> background
&lt;/div&gt;
						</pre></code>
					</div>
					<div class="ma1 pv3 ph2 h4 ba
					b--<%= css_class %>
					<%= css_class %> bg-white">
					<code><pre>
&lt;div class="<%= css_class %> b--<%= css_class %>"&gt;
<%= name %> border and text
&lt;/div&gt;
					</pre></code>
					</div>
				<% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_head.html.erb
<title>WidgetsReload</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><%= Rails.configuration.application_name %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_widget_path %>">New Widget</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/widgets/_rating.html.erb
<%# Widget Rating Component %>

<%# widget:: expected to be a Widget to rate %>
<%# suppress_cta:: if true, suppresses the call-to-action %>
<%# optional, default is false (show CTA) %>



<section>
	<div class="dn" data-rating-present>
		<p>Thanks for rating this a
			<span data-rating-label></span>
		</p>
	</div>
	<div class="cf" data-no-rating-present>
		<h3 style="float: left; margin: 0; padding-right: 1rem;">
    Rate This Widget: <%= widget_presenter.styled_widget_id %>: 
		</h3>
		<ol style="list-style: none; padding: 0; margin: 0">
			<% (1..5).each do |rating| %>
				<li style="float: left">
					<%= button_to rating,
						widget_ratings_path,
						remote: true,
						data: { 
							rating: true
						},
						params: {
							widget_id: widget.id,
							rating: rating
						}
					%>
				</li>
			<% end %>
		</ol>
  </div>
  <% if !local_assigns[:suppress_cta] %>
    <p>Your ratings help us be amazing!</p>
  <% end %>
</section>

app/views/widgets/index.html.erb
<h1>Our Widgets</h1>
<ul>
  <% @widgets.each do |widget| %>
    <li>
      <%= link_to widget.name, widget_path(widget.id) %>
    </li>
  <% end %>
</ul>

app/views/widgets/new.html.erb
<section class="center w-two-thirds helvetica pa3">
  <h1>
    New Widget
  </h1>

  <div class="mb3">
    <%= form_with(model: @widget, local: true) do |f| %>
      <%= f.text_field :name, class:"db w-100 pa2 mb1", 
        autofocus: true, placeholder: "e.g. Stembolt" %>
      <%= f.label :name, class: "fw4 i" %>

      <%= f.text_field :price_cents, class: "db w-100 pa2 mb1", 
        placeholder: "e.g. 123.45" %>
      <%= f.label :price_cents, class: "fw4 i" %>

      <%= f.label :manufacturer_id %>
      <%= f.select :manufacturer_id, options_from_collection_for_select(
        @manufacturers.sort_by(&:name),
        "id", "name"
      ),
      {
        include_blank: "--Choose--",
      },
      {
        class: "db w-100 pa2 mb1"
      }
    %>
  <div class="tr">
    <%= f.submit "Create",
      class: "ba br3 ph3 pv2 white bg-dark-blue"
    %>
  </div>
<% end %>
</section>

app/views/widgets/show.html.erb
<h1>Widget Information</h1>
<h2 data-testid="widget-name"><%= @widget.name %></h2>
<%# <h2>ID #<%= @widget.styled_widget_id %1></h2> %>
<h2>ID #<%= styled_widget_id(@widget.widget_id) %></h2>
<% if flash[:notice].present? %>
  <aside>
    <%= flash[:notice] %>
  </aside>
<% end %>

<%= widget_rating_component(@widget) %>

<%= link_to "/manufacturers/#{ @widget.manufacturer_id }" do %>
  View Manufacturer
<% end %>